name: 'Notification Action Name'
description: 'A Github Action for different chat Apps like slack, teams, mattermost'
inputs:
  message:
    description: "Send notification message"
    required: true
runs:
  using: 'composite'
  steps:
    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install Dependencies
      run: pip install -r requirements.txt
      shell: bash
    - name: Pass Inputs to Shell
      run: |
          echo "INPUT_MESSAGE=${{ inputs.message }}" >> $GITHUB_ENV
      shell: bash
    - name: Send notification message
      id: send-notification-message
      run: python notification.py
      shell: bash